use utf8;
use v5.10;
use strict;
use warnings;

package Davlog::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Davlog::Schema',
    
    connect_info => {
        dsn           => 'dbi:SQLite:data.db',
        user          => '',
        password      => '',
        on_connect_do => q{PRAGMA foreign_keys=ON},
    }
);

=head1 NAME

Davlog::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Davlog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Davlog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Kazuki Matsuda

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

__PACKAGE__->config(
	connect_info => {
		sqlite_unicode => 1,	
	}
);
1;
